name: My First Workflow

on: push

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello Everyone , Good Morning "

  git:
    runs-on: ubuntu-latest
    needs: print

    steps:
      - name: code checkout
        uses: actions/checkout@v5 

      - run: ls -l




