name: My First Workflow

on: push

jobs:
  Test:
    runs-on: self-hosted
   
    steps:
     - name: Code Checkout Repo 
       uses: actions/checkout@v5 

     - name: create a file 
       run: echo "testing self hosted runner" > output.txt  





  



